name: coverage

on:
  workflow_run:
    workflows:
      - "aya-ci"
    branches:
      - main
    types:
      - completed

  workflow_dispatch:

jobs:
  codecov:
    runs-on: ubuntu-latest

    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rust-src

      - uses: Swatinem/rust-cache@v2

      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin -o Xml --skip-clean

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
